version: "3.8"

services:
  portfolio:
    container_name: saintdeniz-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
